name: Deployment(master)

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 12.x]
    defaults:
      run:
        working-directory: spa
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npx yarn install
    - name: Build optimized production page
      run: npx yarn build
    - name: Find?
      run: find -name "*" -not -path "./node_modules/*"
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: spa/build # The folder the action should deploy.
        CLEAN: true # Automatically remove deleted files from the deploy branch
    - name: Updating Domain
      run: echo "Updated domain"
      env:
        CI: true
